apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "test-http-app.fullname" . }}
  labels:
    {{- include "test-http-app.labels" . | nindent 4 }}
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "test-http-app.fullname" . }}
            port: 
              number: {{ .Values.service.port }}
